### ISSUE TITLE
Give a helpful error when publishing an unpublished package

### ISSUE THREAD

**Issue by sparksp** [dillonkearns/elm-publish-action#3]
At the moment, if you add this to an unpublished package you'll get an error:

```
##[error]Request failed with status code 500
```

It would be great if you can give a better error about what the request was, in my case I suspect that it's when fetching a "releases.json" that does not exist (yet).

**Comment by dillonkearns** [comment]
Great idea!

Yeah, the goal of this project is very much to give user's confidence that the right thing will happen in a safe, idempotent, declarative, and intuitive way. Giving very clear error messages (especially the first time you run it) is very important for all of those goals.

Thanks for opening the issue!

**Comment by dillonkearns** [comment]
This was fixed in #7.
